import { AsyncLocalStorage } from 'node:async_hooks';

/**
 * Per-request context propagated automatically through all async operations
 * via Node.js AsyncLocalStorage — no need to pass it as a parameter.
 *
 * Set up by requestContextMiddleware on every incoming request.
 * Read by the Pino mixin so every log line gets requestId + userId automatically.
 */
export interface RequestContext {
  /** UUID generated by pino-http — same ID that appears in HTTP access logs */
  requestId: string;
  /** Populated by authenticate middleware after token verification */
  userId?: string;
}

const storage = new AsyncLocalStorage<RequestContext>();

/**
 * Returns the context for the currently executing request, or undefined
 * if called outside of a request (e.g. worker, startup, scripts).
 */
export function getRequestContext(): RequestContext | undefined {
  return storage.getStore();
}

/**
 * Runs fn() within the given request context.
 * All async operations started inside fn() inherit this context automatically.
 */
export function runWithRequestContext<T>(context: RequestContext, fn: () => T): T {
  return storage.run(context, fn);
}

/**
 * Sets the userId on the current request context.
 * Called by authenticate middleware after successful token verification.
 */
export function setRequestUserId(userId: string): void {
  const ctx = storage.getStore();
  if (ctx) ctx.userId = userId;
}
